apiVersion: v1
kind: Service
metadata:
  name: triton
  namespace: ml-inference
spec:
  type: NodePort
  selector:
    app: triton
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
    - name: grpc
      port: 8001
      targetPort: 8001
      nodePort: 30801
    - name: metrics
      port: 8002
      targetPort: 8002
      nodePort: 30802
